# .scrutinizer.yml

checks:
  php:
    code_rating: true
    duplication: true
build:
  environment:
    mongodb: true
    php: '5.6'
  dependencies:
    before:
      - 'pecl install mongodb'
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=.soupmix_coverage'
        coverage:
          file: '.soupmix_coverage'
          format: 'clover'
filter:
  excluded_paths:
    - "tests/"