language: php

sudo: false
services:
  - mongodb
php:
  - 7.1
  - 7.0
  - 5.6

before_script:
  - pecl install mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sleep 10
  - composer install -n

script:
  - vendor/bin/phpunit

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi